name: build-windows

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master", "rustdesktop" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true
      
      - name: Install deps
        run: |
          choco install nasm
          choco install cmake
          choco install llvm
      
      - name: Build
        run: |
          cargo build --release --features flutter
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk
          path: target/release/rustdesk.exe
